#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

# this script is executed by root
mkdir -p ${HOME}/start_work
chown -R ${USER_NB}:${USER_NB} ${HOME}/start_work
echo "running start"
ls -lR ${HOME}/*
# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
